# 配置数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: rootpassword

  # mongodb
#  data:
#    mongodb:
#      uri: mongodb://root:rootpassword@localhost:27017/mydb?authSource=admin
#      authentication-database: admin

  # rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    virtual-host: /
    listener:
      simple:
        prefetch: 1 # 每次都取一条消息

# Mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mybatis/mapper/mysql/*.xml

# Redis
redis:
  sdk:
    config:
      host: 127.0.0.1
      port: 6379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

# 日志配置,最高优先级,之后才到logback-spring.xml
logging:
  level:
    root: INFO
    org.springframework.web: INFO
  file:
    name: ${user.dir}/logs/spring-boot-app.log
    path: ${user.dir}/logs
