version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7.4.2  # Fixed version of Redis
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3.8-management  # Fixed version of RabbitMQ with management plugin
    container_name: rabbitmq-server
    ports:
      - "5672:5672"  # RabbitMQ AMQP protocol
      - "15672:15672"  # RabbitMQ management web interface
    networks:
      - backend
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

volumes:
  mysql-data:

networks:
  backend:
    driver: bridge
